In [1]:
#### takes images: "IMG_1357.jpg","IMG_1358.jpg",.... and extract mean RGB,HSV, LAB values of reference zone and sample zone

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import cv2
import pandas as pd 
import scipy.io

In [2]:
##### code to extract mean rgb,hsv,lab values from all images and store them in a csv file #######

rgb_list=[]
for i in range (1,602):
    if i >0:

        ## path to the Image dataset directory 
        filename= "C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_"+str(i)+".jpg"
        print (filename) 

        image_name= ["IMG_"+str(i)]

        ## read the image
        image = cv2.imread(filename)
        #image_for_plot= np.copy(image)
        image_for_plot= cv2.cvtColor(image,cv2.COLOR_BGR2LAB)


        # rgb to gray conversion
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        gray_mean= np.mean(gray)
        print (gray_mean)

        #formula to choose right lower binary threshold, self-estimated formula after observance 
        # T= 0.8I-30
        lower_th= 0.8*gray_mean-30

        # threshold, gives binary image
        ret2,th2 = cv2.threshold(gray,lower_th,255,cv2.THRESH_BINARY)


        # find the contour 
        contours= cv2.findContours(th2,cv2.RETR_CCOMP,cv2.CHAIN_APPROX_NONE)
        cnts = contours[1] if cv2.__version__.startswith('3') else contours[0]
        circles= []

        for c in cnts:

            if cv2.contourArea(c) < 2000:
                continue

            (x,y),r = cv2.minEnclosingCircle(c) # get the minimum closing circle
            circles.append([int(x),int(y),int(r)-25])

        # re-arrange the circles from left to right (i.e with the horizontal)
        if circles[0][0]>circles[1][0]:
            circles= circles[0:2][::-1]



        RGB_values=[]  # stores RGB value of reference zone and sample zone

        for cr in circles[0:2]:
            mask = np.zeros(image.shape,np.uint8) # empty array of image size
            cv2.circle(mask,(cr[0],cr[1]),cr[2],(255,255,255),-1) # create a circular mask

            masked_image = cv2.bitwise_and(image_for_plot,mask) # masked image

            pixelpoints = masked_image[~np.all(masked_image == 0, axis=2)] #obtain the RGB,HSV,LAB values of pixel points inside the circle
            RGB_values.append(pixelpoints)

        RGB_values= np.array(RGB_values) 
        mean_ref = np.mean(RGB_values[0], axis=0)
        print (mean_ref)
        mean_sample=np.mean(RGB_values[1], axis=0)
        concat_data=np.concatenate((image_name,mean_ref,mean_sample), axis=0)
        #rgb_list.append(image_name)
        rgb_list.append(concat_data)
        
rgb_list=list(rgb_list)         
#df=pd.DataFrame(rgb_list, columns=["ImageName","BlueReference","GreenReference","RedReference","BlueSample","GreenSample","RedSample"] )
#df=pd.DataFrame(rgb_list, columns=["ImageName","HReference","SReference","VReference","HSample","SSample","VSample"])
df=pd.DataFrame(rgb_list, columns=["ImageName","LReference","aReference","bReference","LSample","aSample","bSample"])
Label_data= pd.read_excel("C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/Labels.xlsx")
result = df.merge(Label_data, on ='ImageName')
result.to_csv("C:/Users/Brinda Khanal/Documents/Bidur Git Repo/padColorimetry/Data/new data/mean_pixel_LAB_pesticide_test_new.csv")
result.head(30)

C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_1.jpg
197.80082017232957
[180.57277731 124.87656899 189.35247667]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_2.jpg
198.14954785018583
[193.26297666 124.9077732  193.38812499]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_3.jpg
196.54054893250193
[170.84198861 127.27037116 189.64952462]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_4.jpg
197.8019504217128
[181.84026039 126.31632743 191.07072373]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_5.jpg
194.78182657611657
[175.70414002 125.62332854 189.78017809]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_6.jpg
196.33692657771851
[185.17206552 127.09424878 192.83473756]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_7.jpg
196.0220095135685
[180.50603357 126.69041565 191.69674973]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/

194.5306152281174
[178.38973379 125.16155631 190.32693515]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_63.jpg
197.39917089180443
[172.99511236 125.80291707 191.21293543]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_64.jpg
184.87234902641612
[162.36163677 127.04708098 186.66469201]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_65.jpg
193.98215367386743
[173.19488479 125.22700354 187.01000802]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_66.jpg
197.30115432866364
[183.98825651 125.40852559 183.75042767]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_67.jpg
194.94425784253653
[174.79190984 128.79488831 187.00704367]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_68.jpg
196.97289003428168
[171.77058353 127.00976061 187.93609323]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_69.jpg
193.026346912846
[178.14079901 127.17108194 189.68281124

192.7449972917067
[163.11003392 129.84680493 191.47273164]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_124.jpg
192.6814949478566
[175.5059011  125.74093702 190.78268362]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_125.jpg
193.93227151716488
[163.31688469 129.74288589 191.68367881]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_126.jpg
193.1277330734173
[168.91094515 130.2613025  191.68995423]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_127.jpg
194.11257739411124
[163.14517603 131.40919108 191.48551465]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_128.jpg
192.2734969472879
[176.17522824 127.48660019 190.08296521]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_129.jpg
189.77060205209534
[179.72472144 124.88066947 187.35771418]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_130.jpg
184.9956121643919
[169.44795383 127.92599445 188.755

176.99767723440752
[143.1386644  123.63122076 185.92834255]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_185.jpg
175.0430789223736
[141.18012313 124.03626027 184.77501546]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_186.jpg
173.98245651028117
[141.63197375 125.16048181 182.68202964]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_187.jpg
175.40625694399282
[143.60600961 125.42722071 183.86102016]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_188.jpg
173.84176596576376
[136.05230473 126.03668311 181.53330124]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_189.jpg
173.02182361445327
[139.77361064 125.35147711 183.34985259]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_190.jpg
172.69381090389786
[139.0467558  124.64121131 183.52825261]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_191.jpg
185.6383650690741
[158.04051797 125.83795099 190.

178.8473290355099
[145.456939   123.11876991 187.33466733]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_246.jpg
177.0711102123439
[138.66989128 125.55620238 185.67836658]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_247.jpg
172.9998818674395
[140.22078994 126.08940853 185.87545687]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_248.jpg
176.80542203894598
[138.30709464 128.35177002 185.56776575]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_249.jpg
170.74439380257928
[141.94674108 124.69792566 186.23064126]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_250.jpg
175.92819962251778
[139.07713799 127.17756473 185.14042138]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_251.jpg
188.33682607703022
[156.15366638 132.19254869 191.52209992]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_252.jpg
184.62751914509624
[156.1164557  128.12774163 190.1

155.20764837542453
[146.8384494  127.90816933 186.82308826]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_307.jpg
129.95254229142637
[118.63388083 129.82424895 177.24095088]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_308.jpg
129.20205982975298
[115.10282491 128.94877248 175.36210643]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_309.jpg
125.01588731897988
[113.16950171 129.06020478 175.64985666]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_310.jpg
130.9201689254133
[115.6758209  130.14993919 177.84245439]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_311.jpg
135.5081282589629
[131.39395868 128.73211955 180.61740459]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_312.jpg
133.06515522875816
[116.82459247 131.1025156  179.51785067]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_313.jpg
132.2901563300974
[119.80835948 131.54837895 180.6

134.91917042312554
[129.77790426 126.9207614  169.82609246]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_368.jpg
135.50693543348712
[123.09692444 127.91198908 173.1578736 ]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_369.jpg
138.53024214945373
[121.22121881 133.16134859 174.72359355]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_370.jpg
138.53961567265796
[128.28665218 133.40773961 171.61519257]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_371.jpg
135.93787239005448
[128.83625517 130.68988435 172.66654456]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_372.jpg
130.66715488534058
[118.80890043 128.37394064 179.32749107]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_373.jpg
133.17809055811867
[122.53002717 129.68698103 180.15687768]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_374.jpg
133.68349588099127
[112.47187929 130.46182734 17

142.94510737556868
[124.28342862 127.24785094 179.13009501]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_429.jpg
136.63583392405164
[110.18539499 130.00215504 175.69466166]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_430.jpg
133.4913970387992
[117.63052943 126.61225477 176.35060468]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_431.jpg
138.642181142269
[126.02496462 124.79682989 176.32901217]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_432.jpg
135.013941703111
[119.86286378 130.46430644 181.22004809]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_433.jpg
135.8064831835512
[126.16254171 127.2365918  181.14142722]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_434.jpg
142.28593081687333
[124.04861519 130.54768897 182.77919848]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_435.jpg
135.48140651532262
[106.24675913 134.62553071 177.3873

[138.0583697  134.09852653 185.81616392]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_490.jpg
147.94254329931863
[137.98400051 133.82394233 186.21513944]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_491.jpg
144.8418488548742
[137.12871608 133.13449535 185.36446438]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_492.jpg
155.26887445133283
[140.79444241 131.68810508 186.74184939]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_493.jpg
155.77051477930496
[142.57471831 131.10553537 187.03491164]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_494.jpg
155.55244594093085
[142.23972051 129.38414405 187.30610051]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_495.jpg
157.50860913537528
[151.09929239 126.37214832 189.31446363]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_496.jpg
151.8228177130057
[134.37191745 131.08149585 184.98292468]
C:/Users/

143.49735011106839
[138.9954518  130.17609177 185.86902797]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_551.jpg
141.00785905661283
[126.38619219 133.34866474 183.07995671]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_552.jpg
152.35391903220983
[143.4322494  130.01929589 185.46079011]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_553.jpg
151.22939043877355
[136.33768145 130.53100542 183.22409526]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_554.jpg
154.08746736031014
[133.06629207 131.42907526 183.56644151]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_555.jpg
152.10353957078473
[134.47544396 130.34033695 181.98204645]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_556.jpg
154.39412442196377
[142.77889807 130.74910557 186.16802186]
C:/Users/Brinda Khanal/Desktop/All pesticide test data/combined/IMG_557.jpg
146.40666784142851
[125.74038766 135.20137351 18

ImageName          LReference          aReference          bReference  \
0      IMG_1  180.57277730644566  124.87656899214689  189.35247666905957   
1      IMG_2  193.26297666410738  124.90777320211257   193.3881249854587   
2      IMG_3  170.84198860653666  127.27037116248323  189.64952462426845   
3      IMG_4  181.84026039058588  126.31632743232495   191.0707237326578   
4      IMG_5   175.7041400201952  125.62332853951837  189.78017808512593   
5      IMG_6  185.17206551886545  127.09424878329582  192.83473755821865   
6      IMG_7  180.50603356604557  126.69041564566092  191.69674973415323   
7      IMG_8  183.87717811751705  126.83658132252717   191.5184380180512   
8      IMG_9  177.37742988359665  128.27737500361053  192.33378585251725   
9     IMG_10  196.47702961927365  125.52957050427545  193.01547615177032   
10    IMG_11  164.89872692832915   122.5347341526805   183.3598079379763   
11    IMG_12  173.21848393863365  121.71690042364168   182.9894295233003   
12    IMG_13  184.20534537925843  121.06884999058911  183.97319781667608   
13    IMG_14  172.30982004399726  121.79710772115835   185.2063904215803   
14    IMG_15   195.2037593057212  120.19462838810513  185.12664006909884   
15    IMG_16   175.7013242320819  123.91153583617748  186.39986348122866   
16    IMG_17  171.89567009507513  123.89730328777244  186.02319522485564   
17    IMG_18   186.2122388228423  123.96951598620872  187.24905326224166   
18    IMG_19  179.83294058431903  121.97664096639136  183.86227092818413   
19    IMG_20  174.91911332434208  123.53829927032541  187.87152885845697   
20    IMG_21  175.74344742522356   127.4290119378001  189.32033831108762   
21    IMG_22  172.89952391103532  127.58217863994884  188.98145384779366   
22    IMG_23  183.75264690924223  125.37158444680753  188.27680429053586   
23    IMG_24  169.78856520074228  127.55450823293764  188.91820083065775   
24    IMG_25  179.75454613484996   124.6324428147372  186.92830951133726   
25    IMG_26  182.92602755552988  124.52826319285982  190.58502065220532   
26    IMG_27   175.6186952116647  125.36456543764592  190.28844544293202   
27    IMG_28  198.20093620835615  122.55564961904288   188.9053333997311   
28    IMG_29  170.53392778093973  124.70442041358376  188.18497438816163   
29    IMG_30  184.76552125087971  123.28854686209112  188.49175361831033   

               LSample             aSample             bSample  \
0    200.5667052753501   122.4896704222386   145.9507633989681   
1   192.20414008906005   122.7914309784571  148.35238897580936   
2    187.6236837842216  122.63795741310726  151.29015245603614   
3   189.57851194539248  122.51721501706484   148.9400409556314   
4   183.43320446138014   123.3520151308653    145.884209940756   
5   192.95318958219212  123.41282804641203  146.91912753348936   
6   193.59703815894653  123.67259876309478  145.08826622912196   
7    202.8710375419236  123.62245302751631  147.27595657975405   
8   201.60956868865745  122.86910586187231   151.9665336014647   
9    195.9264729286692  123.03020657605755   148.0399146958653   
10  180.65228416180318  121.12819480780841  135.45232441135036   
11   176.4901185770751  121.03301336344815  138.78516845473368   
12    193.858445205216  121.78347501634804  136.26960803169595   
13  194.06975246528478  120.09390219360033  141.61879653853893   
14  189.66870597705775  120.64672972429061  138.07542765143893   
15  185.16297622495458  122.35933756351861   150.6107790737474   
16  179.10038339003185  123.20726461112011   145.3840200154796   
17   188.8226915613166  122.99316087947699  147.88070162217156   
18  183.42149253731344  122.49618573797679  147.69519071310117   
19   181.9145175515964  122.27204092432528  151.47521608749338   
20  185.49597277856742  123.25494249903089  148.38725933583152   
21  186.79041709755256  121.93291968286798  151.43267838676317   
22   188.4549118632545  122.81348030884281  148.00291361142135   
23  178.26830146771917  122.16063871296936  154.71843203169553